### PR TITLE
fix: Set lower bound on required Python to 3.8

### PR DESCRIPTION
**Pull request by matthewfeickert**
Resolves https://github.com/Anaconda-Platform/anaconda-client/issues/678

The walrus operator is used in v1.12.0 which is a Python 3.8+ only operation.

@jakirkham, @goanpeca, @beckermr as you are listed as being the recipe maintainers please review this.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [N/A] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@conda-forge-admin, please rerender

**Comment by matthewfeickert** [comment]
@jakirkham, @goanpeca, @beckermr Please also note and escalate https://github.com/Anaconda-Platform/anaconda-client/pull/681.

**Review by chenghlee — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks all! 🙏

Do we need a repodata patch as well?

**Comment by matthewfeickert** [comment]
> Do we need a repodata patch as well?

I don't actually know what that is, despite maintaining multiple conda-forge recipes :grimacing:. So I guess next week I should read Wolf's https://prefix.dev/blog/repodata_patching and teach myself.

**Comment by jakirkham** [comment]
Here's a relevant example ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/456 )

Please give it a try and ask any questions 🙂

**Comment by matthewfeickert** [comment]
Maybe the Anaconda engineers who are responsible for maintaining this could fix it instead?

**Pull request merged**
