### PR TITLE
ENH backport patch for python 3.9

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
cc @conda-forge/core this should solve our upload woes maybe?

**Review by chrisburr — APPROVED** [review]
Thanks for doing this!

**Comment by beckermr** [comment]
One worry is that it won't upload due to its own bug! Maybe I will force python 3.8 in the CI before we merge.

**Comment by chrisburr** [comment]
I've confirmed this works locally.

> One worry is that it won't upload due to its own bug! Maybe I will force python 3.8 in the CI before we merge.

I think this shouldn't be needed as the docker container hasn't been updated to Python 3.9 yet.

**Comment by beckermr** [comment]
Let's merge and get this fixed!

**Pull request merged**
